Repository Activiti/activiti-cloud-service-common, pull requests merged in 2018-11, with the labels that each got.

#86 update org.activiti.core.common:activiti-core-common-dependencies to 7.0.7
  pom.xml
Labels: updatebot

#87 update org.activiti.cloud.api:activiti-cloud-api-dependencies to 7.0.19
  pom.xml
Labels: updatebot

#90 update org.activiti.core.common:activiti-core-common-dependencies to 7.0.9
  pom.xml
Labels: updatebot

#91 update org.activiti.cloud.api:activiti-cloud-api-dependencies to 7.0.21
  pom.xml
Labels: updatebot

#96 Add rest docs helper for process definitions in HAL format
  activiti-cloud-services-rest-docs/src/main/java/org/activiti/alfresco/rest/docs/AlfrescoDocumentation.java
  activiti-cloud-services-rest-docs/src/main/java/org/activiti/alfresco/rest/docs/HALDocumentation.java
Labels: in progress

#95 update org.activiti.cloud.build:activiti-cloud-parent to 7.0.35
  pom.xml
Labels: in progress, updatebot

#94 update org.activiti.dependencies:activiti-dependencies to 7.0.61
  pom.xml
Labels: in progress, updatebot

#100 update org.activiti.dependencies:activiti-dependencies to 7.0.62
  pom.xml
Labels: in progress, updatebot

#102 fix: add activiti-cloud-service-common-dependencies-tests module
  .mergify.yml
  .updatebot.yml
  activiti-cloud-service-common-dependencies/pom.xml
  activiti-cloud-services-auditable/pom.xml
  activiti-cloud-services-common-identity-keycloak/pom.xml
  activiti-cloud-services-common-security-keycloak/pom.xml
  activiti-cloud-services-common-security/pom.xml
  activiti-cloud-services-commons-io/pom.xml
  activiti-cloud-services-dbp-rest/pom.xml
  activiti-cloud-services-logging/pom.xml
  activiti-cloud-services-metadata/pom.xml
  activiti-cloud-services-monitoring/pom.xml
  activiti-cloud-services-rest-docs/pom.xml
  activiti-cloud-services-test/pom.xml
  activiti-cloud-services-tracing/pom.xml
  dependencies-tests/pom.xml
  pom.xml
Labels: enhancement, in progress

#104 Ryan 2201 temp override keycloakadapter
  activiti-cloud-services-common-security-keycloak/src/main/java/org/keycloak/adapters/springsecurity/KeycloakConfiguration.java
Labels: in progress

#105 fix(versions): update Activiti/activiti-cloud-service-common versions
  pom.xml
Labels: in progress, updatebot

#106 shouldn't add the same same componentscan that removing from keycloak
  activiti-cloud-services-common-security-keycloak/src/main/java/org/activiti/cloud/services/common/security/keycloak/config/CommonSecurityAutoConfiguration.java
Labels: in progress

#107 just this is enough to avoid bean overriding
  activiti-cloud-services-common-security-keycloak/src/main/java/org/activiti/cloud/services/common/security/keycloak/config/CommonSecurityAutoConfiguration.java
  activiti-cloud-services-common-security-keycloak/src/main/java/org/keycloak/adapters/springsecurity/KeycloakConfiguration.java
Labels: in progress

#108 need this to avoid seeing bean override exception at example layer
  activiti-cloud-services-metadata/src/main/java/org/activiti/cloud/services/metadata/ActivitiMetadataAutoConfiguration.java
Labels: in progress
